import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeNav from "./navigation";
import 'react-toastify/dist/ReactToastify.css';

import { ToastContainer } from 'react-toastify';

import { CookiesProvider } from 'next-client-cookies/server';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div>
            <CookiesProvider>
              <HomeNav />
              <div className="flex min-h-screen flex-col justify-between py-24 px-12">
                  {children}
                <ToastContainer />
              </div>
            </CookiesProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
