import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeNav from "./navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeNav />
        <main className="flex min-h-screen flex-col justify-between py-24 px-12">
          {children}
        </main>
      </body>
    </html>
  );
}
